//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var MemberRole = &struct {
	Admin     postgres.StringExpression
	Moderator postgres.StringExpression
	Guest     postgres.StringExpression
}{
	Admin:     postgres.NewEnumValue("ADMIN"),
	Moderator: postgres.NewEnumValue("MODERATOR"),
	Guest:     postgres.NewEnumValue("GUEST"),
}
